name: Epic
description: Epic template for this project
title: "[EPIC]: "
labels: ["epic"]
projects: ["Proyecto Grupo 005"]

body:
  - type: textarea
    id: epic_description
    attributes:
      label: Epic Description
      description: Describe the epic
      placeholder: What is this epic about?
    validations:
      required: true
